#!/usr/bin/env python3
"""Generate ``resources.qrc`` and compile it into ``resources_rc.py``.

Resources are discovered automatically, so adding a game is a matter of
dropping files into ``games/<name>/{icons,styles,i18n}`` — no manual edits to
the ``.qrc`` are required.  Discovery covers two locations:

* shared, framework-wide assets under ``core/resources/{icons,styles,i18n}``
* per-game assets under ``games/<name>/{icons,styles,i18n}``

Every file is exposed under a flat resource alias (``:/icons/<name>``,
``:/styles/<name>``, ``:/i18n/<name>``) regardless of where it physically
lives, which keeps existing ``:/`` references and ``BonusButton`` paths working.
Because the namespace is flat, file names must be unique across all games; a
collision is reported as an error rather than silently resolved.

Usage (from the repository root)::

    python utils/build_resources.py
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

# category -> accepted file suffixes
CATEGORIES = {
    "icons": {".svg", ".png", ".ico"},
    "styles": {".qss"},
    "i18n": {".qm"},  # only compiled catalogues; .ts sources stay out of the bundle
}

PROJECT_ROOT = Path(__file__).resolve().parent.parent
QRC_PATH = PROJECT_ROOT / "resources.qrc"
OUTPUT_PATH = PROJECT_ROOT / "resources_rc.py"


def _resource_dirs(category: str) -> list[Path]:
    """Directories to scan for a category: shared first, then each game."""
    dirs = [PROJECT_ROOT / "core" / "resources" / category]
    dirs += sorted(
        game_dir / category
        for game_dir in (PROJECT_ROOT / "games").iterdir()
        if game_dir.is_dir() and (game_dir / category).is_dir()
    )
    return [d for d in dirs if d.is_dir()]


def collect_entries() -> list[tuple[str, Path]]:
    """Return ``(alias, path)`` pairs, erroring on duplicate aliases."""
    entries: dict[str, Path] = {}
    for category, suffixes in CATEGORIES.items():
        for directory in _resource_dirs(category):
            for path in sorted(directory.iterdir()):
                if not path.is_file() or path.suffix.lower() not in suffixes:
                    continue
                alias = f"{category}/{path.name}"
                if alias in entries:
                    raise SystemExit(
                        f"Duplicate resource '{alias}':\n"
                        f"  {entries[alias].relative_to(PROJECT_ROOT)}\n"
                        f"  {path.relative_to(PROJECT_ROOT)}\n"
                        "Resource names must be unique across all games."
                    )
                entries[alias] = path
    return sorted(entries.items())


def write_qrc(entries: list[tuple[str, Path]]) -> None:
    lines = [
        "<!-- AUTO-GENERATED by utils/build_resources.py — do not edit by hand. -->",
        "<RCC>",
        '    <qresource prefix="/">',
    ]
    for alias, path in entries:
        rel = path.relative_to(PROJECT_ROOT).as_posix()
        lines.append(f'        <file alias="{alias}">{rel}</file>')
    lines += ["    </qresource>", "</RCC>", ""]
    QRC_PATH.write_text("\n".join(lines))


def compile_qrc() -> None:
    rcc = Path(sys.executable).parent / "pyside6-rcc"
    cmd = [
        str(rcc) if rcc.exists() else "pyside6-rcc",
        str(QRC_PATH),
        "-o",
        str(OUTPUT_PATH),
    ]
    subprocess.run(cmd, check=True)


def main() -> None:
    entries = collect_entries()
    write_qrc(entries)
    compile_qrc()
    by_cat: dict[str, int] = {}
    for alias, _ in entries:
        by_cat[alias.split("/", 1)[0]] = by_cat.get(alias.split("/", 1)[0], 0) + 1
    summary = ", ".join(f"{n} {cat}" for cat, n in sorted(by_cat.items()))
    print(f"Wrote {QRC_PATH.name} and {OUTPUT_PATH.name} ({summary}).")


if __name__ == "__main__":
    main()
